version: 2.1
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                  name: "Build image"
                  command: |
                      docker build . -t symfony